"area: pet-content":
  - changed-files:
      - any-glob-to-any-file:
          - "src/pet-content/**"

"area: service-worker":
  - changed-files:
      - any-glob-to-any-file:
          - "src/service/**"

"area: docs":
  - changed-files:
      - any-glob-to-any-file:
          - "README.md"
          - "docs/**"
          - "CONTRIBUTING.md"
          - "SECURITY.md"

"area: automation":
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"

"area: evals":
  - changed-files:
      - any-glob-to-any-file:
          - "scripts/**"
